const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {initializeApp}=require('firebase-admin/app');
const {getAuth}=require('firebase-admin/auth');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
const {getStorage}=require('firebase-admin/storage');
const {randomUUID}=require('crypto');
initializeApp();
const db=getFirestore(),auth=getAuth(),bucket=getStorage().bucket();
const VALID_ROLES=['editor','validator','admin','super_admin'];
const ROLE_ALIASES={editor:'editor',validator:'validator',validador:'validator',admin:'admin',administrador:'admin',super_admin:'super_admin','super-admin':'super_admin','super admin':'super_admin',superadmin:'super_admin','super administrador':'super_admin','administrador principal':'super_admin'};
const normalizeRole=r=>ROLE_ALIASES[String(r||'').trim().toLowerCase()]||String(r||'guest').trim().toLowerCase();
const n=v=>Math.max(0,Number(v)||0);const clean=(v,max=800)=>String(v??'').trim().slice(0,max);const slug=s=>clean(s,150).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const PUBLIC_KEYS=['meta','documentControl','executiveSummary','objective','scope','limitations','eventContext','regulatoryFramework','rufeRud','kpis','completeness','componentStatus','housing','housingInterpretation','priorityHousingNarrative','sexDistribution','lifeCycle','locationDeclared','territorialReading','qualityIssues','qualityAssuranceRules','methodology','appliedRules','priorities','prioritizationMatrix','conclusions','annexIndicators','visualReports'];
const TERRITORY_KEYS=['sector','families','people','noHab','destroyed','noState','empty','lat','lng','precision','reference','source'];

async function profile(uid,email){const a=await db.doc(`users/${uid}`).get();if(a.exists)return {docId:uid,...a.data()};if(email){const b=await db.doc(`users/${email}`).get();if(b.exists)return {docId:email,legacy:true,...b.data()}}return null}
async function requireRole(req,roles){if(!req.auth)throw new HttpsError('unauthenticated','Debes iniciar sesión.');const p=await profile(req.auth.uid,req.auth.token?.email||'');const role=normalizeRole(p?.role);if(!p||p.active!==true||!roles.includes(role))throw new HttpsError('permission-denied','No tienes permisos para esta operación.');return {uid:req.auth.uid,email:req.auth.token?.email||p.email||'',role,profile:p}}
async function audit(actor,action,eventId,detail='',meta={}){await db.collection('rufeAudit').add({actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,action,eventId:eventId||null,detail,meta,createdAt:FieldValue.serverTimestamp()})}
function stripTerritory(x){const o={};for(const k of TERRITORY_KEYS)if(x[k]!==undefined)o[k]=x[k];return o}
function itemCount(arr,label){return n((Array.isArray(arr)?arr:[]).find(x=>x.label===label)?.count)}
function updateByLabel(arr,label,patch){return (Array.isArray(arr)?arr:[]).map(x=>x.label===label?{...x,...patch}:x)}
function consistency(payload,totals){const k=payload.kpis||{},people=totals.people,families=totals.families;const sex=n(k.women)+n(k.men)+n(k.sexMissing);if(sex&&sex!==people)throw new HttpsError('failed-precondition',`La distribución por sexo suma ${sex}, pero el total territorial es ${people}.`);const life=(payload.lifeCycle||[]).reduce((s,x)=>s+n(x.count),0);if(life&&life!==people)throw new HttpsError('failed-precondition',`El ciclo de vida suma ${life}, pero el total territorial es ${people}.`);const loc=(payload.locationDeclared||[]).reduce((s,x)=>s+n(x.count),0);if(loc&&loc!==families)throw new HttpsError('failed-precondition',`La ubicación declarada suma ${loc}, pero el total de familias es ${families}.`);for(const [label,v] of [['Dirección',k.familiesWithAddress],['Teléfono',k.familiesWithPhone]])if(n(v)>families)throw new HttpsError('failed-precondition',`${label} no puede superar ${families} familias.`);if(n(k.uniquePeopleEstimated)>people)throw new HttpsError('failed-precondition','Las personas únicas estimadas no pueden superar los registros nominales.')}
function derive(draft,territories){
  const families=territories.reduce((s,t)=>s+n(t.families),0),people=territories.reduce((s,t)=>s+n(t.people),0),noHab=territories.reduce((s,t)=>s+n(t.noHab),0),destroyed=territories.reduce((s,t)=>s+n(t.destroyed),0),empty=territories.reduce((s,t)=>s+n(t.empty),0),without=territories.reduce((s,t)=>s+Math.max(0,n(t.noState)-n(t.empty)),0),withState=Math.max(0,families-without);
  const out={};for(const k of PUBLIC_KEYS)if(draft[k]!==undefined)out[k]=draft[k];out.kpis={...(out.kpis||{}),families,nominalPeople:people,territories:territories.length,familiesWithoutState:without,familiesWithState:withState,emptyPreEnumerated:empty};
  out.housing=updateByLabel(out.housing,'No habitable',{count:noHab,pct:families?noHab/families*100:0});out.housing=updateByLabel(out.housing,'Destruida',{count:destroyed,pct:families?destroyed/families*100:0});out.housing=updateByLabel(out.housing,'Sin clasificación registrada',{count:without,pct:families?without/families*100:0});
  const hab=itemCount(out.housing,'Habitable'),dam=itemCount(out.housing,'Averiada');out.housing=updateByLabel(out.housing,'Habitable',{count:hab,pct:families?hab/families*100:0});out.housing=updateByLabel(out.housing,'Averiada',{count:dam,pct:families?dam/families*100:0});
  if(Array.isArray(out.lifeCycle)){out.kpis.minors=itemCount(out.lifeCycle,'0–5')+itemCount(out.lifeCycle,'6–11')+itemCount(out.lifeCycle,'12–17');out.kpis.age60plus=itemCount(out.lifeCycle,'60 y más');out.lifeCycle=out.lifeCycle.map(x=>({...x,pct:people?n(x.count)/people*100:0}))}
  if(Array.isArray(out.locationDeclared)){out.kpis.familiesWithUrbanRural=itemCount(out.locationDeclared,'Rural')+itemCount(out.locationDeclared,'Urbana')}
  out.sexDistribution=[{label:'Femenino',count:n(out.kpis.women),pct:people?n(out.kpis.women)/people*100:0,tone:'magenta'},{label:'Masculino',count:n(out.kpis.men),pct:people?n(out.kpis.men)/people*100:0,tone:'blue'},{label:'Sin dato',count:n(out.kpis.sexMissing),pct:people?n(out.kpis.sexMissing)/people*100:0,tone:'gray'}];
  if(Array.isArray(out.completeness))out.completeness=out.completeness.map(x=>{let num=x.numerator,den=x.denominator;if(x.label==='Integrante nominal'){num=families;den=families}else if(x.label==='Teléfono'){num=n(out.kpis.familiesWithPhone);den=families}else if(x.label==='Dirección'){num=n(out.kpis.familiesWithAddress);den=families}else if(x.label==='Estado del inmueble'){num=withState;den=families}else if(x.label==='Fecha de nacimiento válida'){num=Math.max(0,people-n(out.kpis.invalidBirthDates));den=people}else if(x.label==='Sexo F/M válido'){num=Math.max(0,people-n(out.kpis.sexMissing));den=people}return {...x,numerator:num,denominator:den,value:den?num/den*100:0}});
  if(Array.isArray(out.qualityIssues)){const counts={'Núcleos numerados sin integrantes':empty,'Grupos de documento repetido':n(out.kpis.repeatedDocGroups),'Jefaturas con documento repetido':n(out.kpis.repeatedHeads),'Personas sin documento válido':n(out.kpis.peopleWithoutValidDocument),'Fecha de nacimiento inválida/ausente':n(out.kpis.invalidBirthDates),'Sexo sin dato F/M':n(out.kpis.sexMissing),'Familias nominales sin estado':without,'Registros con marcas múltiples':n(out.kpis.multipleHousingMarks),'Zona urbana/rural sin dato homologable':n(out.kpis.noZoneHomologable)};out.qualityIssues=out.qualityIssues.map(x=>counts[x.label]===undefined?x:{...x,count:counts[x.label]})}
  if(Array.isArray(out.componentStatus))out.componentStatus=out.componentStatus.map(x=>x.component==='Cobertura territorial'?{...x,progress:`${territories.length} hojas territoriales únicas analizadas`}:x.component==='Identificación familiar'?{...x,progress:`${families} núcleos con al menos una persona`,status:`En curso; ${empty} núcleos preenumerados están vacíos`}:x.component==='Caracterización individual'?{...x,progress:`${people.toLocaleString('es-CO')} registros nominales`}:x.component==='Clasificación del inmueble'?{...x,progress:`${withState} de ${families} familias`,status:`En curso; ${without} sin marca y ${n(out.kpis.multipleHousingMarks)} con marcas múltiples`}:x);
  if(Array.isArray(out.annexIndicators)){const map={'Territorios/sectores únicos':String(territories.length),'Registros con integrante nominal':String(families),'Núcleos numerados vacíos':String(empty),'Registros nominales':people.toLocaleString('es-CO'),'Únicas estimadas':n(out.kpis.uniquePeopleEstimated).toLocaleString('es-CO'),'Documentos repetidos — grupos':String(n(out.kpis.repeatedDocGroups)),'0–17 años':String(n(out.kpis.minors)),'60 años y más':String(n(out.kpis.age60plus)),'Familias nominales sin estado':String(without),'Marcas múltiples':String(n(out.kpis.multipleHousingMarks))};out.annexIndicators=out.annexIndicators.map(x=>map[x.indicator]!==undefined?{...x,value:map[x.indicator]}:x)}
  out.territories=territories.map(stripTerritory);consistency(out,{families,people});return out;
}
function validateTerritories(territories){for(const t of territories){const sector=clean(t.sector,160)||'Territorio sin nombre',families=n(t.families),people=n(t.people),noState=n(t.noState),empty=n(t.empty);if(people<families)throw new HttpsError('failed-precondition',`${sector}: personas (${people}) no puede ser menor que familias (${families}).`);if(noState<empty)throw new HttpsError('failed-precondition',`${sector}: “sin estado” (${noState}) debe incluir como mínimo los núcleos vacíos (${empty}).`);for(const [label,value] of [['No habitable',n(t.noHab)],['Destruida',n(t.destroyed)]])if(value>families)throw new HttpsError('failed-precondition',`${sector}: ${label} (${value}) no puede superar las familias (${families}).`);if(t.lat!=null&&(Number(t.lat)<-90||Number(t.lat)>90))throw new HttpsError('failed-precondition',`${sector}: latitud fuera de rango.`);if(t.lng!=null&&(Number(t.lng)<-180||Number(t.lng)>180))throw new HttpsError('failed-precondition',`${sector}: longitud fuera de rango.`)}}
async function loadEvent(eventId){const [draftSnap,terrSnap,wfSnap]=await Promise.all([db.doc(`rufeEvents/${eventId}/drafts/current`).get(),db.collection(`rufeEvents/${eventId}/territories`).get(),db.doc(`rufeEvents/${eventId}/workflow/state`).get()]);if(!draftSnap.exists)throw new HttpsError('failed-precondition','No existe borrador inicial.');return {draft:draftSnap.data(),territories:terrSnap.docs.map(d=>d.data()).sort((a,b)=>clean(a.sector).localeCompare(clean(b.sector),'es')),workflow:wfSnap.exists?wfSnap.data():{revision:0,reviewStatus:'draft'}}}

exports.adminCreateRufeUser=onCall(async req=>{const actor=await requireRole(req,['super_admin']),eventId=clean(req.data?.eventId,120),email=clean(req.data?.email,240).toLowerCase(),password=String(req.data?.password||''),displayName=clean(req.data?.displayName,160),role=normalizeRole(req.data?.role);if(!email||!email.includes('@'))throw new HttpsError('invalid-argument','Correo inválido.');if(password.length<8)throw new HttpsError('invalid-argument','La contraseña temporal debe tener al menos 8 caracteres.');if(!VALID_ROLES.includes(role))throw new HttpsError('invalid-argument','Rol inválido.');const u=await auth.createUser({email,password,displayName,emailVerified:false,disabled:false});await db.doc(`users/${u.uid}`).set({uid:u.uid,email,displayName,role,active:true,rufeAccess:true,createdAt:FieldValue.serverTimestamp(),createdBy:actor.uid});await audit(actor,'user.create',eventId,`Creó ${email}`,{uid:u.uid,role});return {uid:u.uid,email,role}});
exports.adminManageRufeUser=onCall(async req=>{const actor=await requireRole(req,['super_admin']),eventId=clean(req.data?.eventId,120),uid=clean(req.data?.uid,180),action=clean(req.data?.action,30);if(!uid)throw new HttpsError('invalid-argument','UID requerido.');if(uid===actor.uid&&action==='active'&&req.data?.active===false)throw new HttpsError('failed-precondition','No puedes desactivar tu propia cuenta.');const ref=db.doc(`users/${uid}`),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Perfil no encontrado.');if(action==='role'){const role=normalizeRole(req.data?.role);if(!VALID_ROLES.includes(role))throw new HttpsError('invalid-argument','Rol inválido.');if(uid===actor.uid&&role!=='super_admin')throw new HttpsError('failed-precondition','No puedes retirar tu propio rol Super Admin.');await ref.update({role,rufeAccess:true,updatedAt:FieldValue.serverTimestamp(),updatedBy:actor.uid});await audit(actor,'user.role',eventId,`Rol de ${uid}: ${role}`);return {ok:true}}if(action==='active'){const active=req.data?.active===true;await ref.update({active,updatedAt:FieldValue.serverTimestamp(),updatedBy:actor.uid});try{await auth.updateUser(uid,{disabled:!active})}catch(_){}await audit(actor,'user.active',eventId,`${uid}: ${active}`);return {ok:true}}if(action==='delete'){if(uid===actor.uid)throw new HttpsError('failed-precondition','No puedes eliminar tu propia cuenta.');const deletedEmail=snap.data()?.email||uid;await auth.deleteUser(uid);await ref.delete();await audit(actor,'user.delete',eventId,`Eliminó ${deletedEmail}`,{uid});return {ok:true}}throw new HttpsError('invalid-argument','Acción no soportada.');});
exports.validateRufeDraft=onCall(async req=>{const actor=await requireRole(req,['editor','validator','admin','super_admin']),eventId=clean(req.data?.eventId,120),{draft,territories,workflow}=await loadEvent(eventId);validateTerritories(territories);const payload=derive(draft,territories),revision=n(workflow.revision);await audit(actor,'workflow.validate',eventId,'Comprobación de consistencia superada',{revision,families:payload.kpis?.families||0,people:payload.kpis?.nominalPeople||0});return {ok:true,revision,families:payload.kpis?.families||0,people:payload.kpis?.nominalPeople||0,territories:territories.length}});
exports.submitRufeForReview=onCall(async req=>{const actor=await requireRole(req,['editor','admin','super_admin']),eventId=clean(req.data?.eventId,120),loaded=await loadEvent(eventId);validateTerritories(loaded.territories);derive(loaded.draft,loaded.territories);const ref=db.doc(`rufeEvents/${eventId}/workflow/state`),w=loaded.workflow||{revision:1},revision=n(w.revision)||1;await ref.set({revision,reviewStatus:'in_review',submittedRevision:revision,approvedRevision:null,submittedAt:FieldValue.serverTimestamp(),submittedBy:actor.uid,reviewNote:clean(req.data?.note,2000),updatedAt:FieldValue.serverTimestamp()},{merge:true});await audit(actor,'workflow.submit',eventId,'Borrador validado y enviado a revisión',{revision});return {ok:true,revision}});
exports.reviewRufeDraft=onCall(async req=>{const actor=await requireRole(req,['validator','admin','super_admin']),eventId=clean(req.data?.eventId,120),decision=clean(req.data?.decision,20),loaded=await loadEvent(eventId),ref=db.doc(`rufeEvents/${eventId}/workflow/state`),w=loaded.workflow||{};const revision=n(w.revision);if(decision==='approve'){if(w.reviewStatus!=='in_review')throw new HttpsError('failed-precondition','El borrador no está en revisión.');if(n(w.submittedRevision)!==revision)throw new HttpsError('failed-precondition','El borrador cambió después de enviarse a revisión.');validateTerritories(loaded.territories);derive(loaded.draft,loaded.territories);await ref.update({reviewStatus:'approved',approvedRevision:revision,approvedAt:FieldValue.serverTimestamp(),approvedBy:actor.uid,approvalNote:clean(req.data?.note,2000),updatedAt:FieldValue.serverTimestamp()});await audit(actor,'workflow.approve',eventId,'Revisión aprobada después del control de consistencia',{revision});return {ok:true,revision}}if(decision==='reject'){await ref.update({reviewStatus:'changes',approvedRevision:null,rejectedAt:FieldValue.serverTimestamp(),rejectedBy:actor.uid,rejectionNote:clean(req.data?.note,2000),updatedAt:FieldValue.serverTimestamp()});await audit(actor,'workflow.reject',eventId,'Ajustes solicitados',{revision});return {ok:true,revision}}throw new HttpsError('invalid-argument','Decisión inválida.');});
exports.publishRufeSnapshot=onCall(async req=>{const actor=await requireRole(req,['super_admin']),eventId=clean(req.data?.eventId,120),version=clean(req.data?.version,40)||'1.0',cutoffDate=clean(req.data?.cutoffDate,20),changeNote=clean(req.data?.changeNote,3000),{draft,territories,workflow}=await loadEvent(eventId),revision=n(workflow.revision);validateTerritories(territories);if(workflow.reviewStatus!=='approved'||n(workflow.approvedRevision)!==revision)throw new HttpsError('failed-precondition','La revisión actual no está aprobada.');if(!cutoffDate)throw new HttpsError('invalid-argument','Fecha de corte requerida.');const payload=derive(draft,territories);
  const mediaSnap=await db.collection(`rufeEvents/${eventId}/media`).where('includeInPublication','==',true).get(),media=[];for(const mdoc of mediaSnap.docs){const m=mdoc.data();if(!m.path)continue;const dest=`rufe-public/${eventId}/${slug(version)}-${cutoffDate}/${mdoc.id}-${String(m.name||'archivo').replace(/[^a-zA-Z0-9._-]+/g,'-')}`;const src=bucket.file(m.path),dst=bucket.file(dest);await src.copy(dst);const token=randomUUID();await dst.setMetadata({contentType:m.contentType||'application/octet-stream',metadata:{firebaseStorageDownloadTokens:token}});const publicUrl=`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(dest)}?alt=media&token=${token}`;media.push({id:mdoc.id,title:m.title||m.name,name:m.name,type:m.type||'annex',size:m.size||0,publicUrl,status:'published',publishedAt:new Date().toISOString()})}
  const currentRef=db.doc(`rufePublished/${eventId}`),currentSnap=await currentRef.get(),current=currentSnap.exists?currentSnap.data():{},summary={id:`${slug(version)}-${cutoffDate}`,version,cutoffDate,publishedAt:new Date().toISOString(),changeNote,kpis:payload.kpis,housing:payload.housing},history=[...(Array.isArray(current.releases)?current.releases:[]).filter(x=>x.id!==summary.id),summary].slice(-50),updates=[...(Array.isArray(current.updates)?current.updates:[]).filter(x=>x.id!==summary.id),{id:summary.id,date:cutoffDate,version,title:`Consolidado técnico v${version}`,note:changeNote||'Nuevo corte publicado.',status:'published'}].slice(-50);const publication={status:'published',version,cutoffDate,publishedAt:summary.publishedAt,revision,publishedBy:actor.email||actor.uid};const snapshot={...payload,media,releases:history,updates,publication};const releaseRef=db.doc(`rufeEvents/${eventId}/releases/${summary.id}`),publicReleaseRef=db.doc(`rufePublished/${eventId}/releases/${summary.id}`),batch=db.batch();batch.set(currentRef,snapshot);batch.set(publicReleaseRef,snapshot);batch.set(releaseRef,{...snapshot,createdAt:FieldValue.serverTimestamp()});batch.set(db.doc(`rufeEvents/${eventId}/workflow/state`),{reviewStatus:'published',publishedRevision:revision,publishedAt:FieldValue.serverTimestamp(),publishedBy:actor.uid,updatedAt:FieldValue.serverTimestamp()},{merge:true});await batch.commit();await audit(actor,'publication.publish',eventId,`Publicó v${version} · ${cutoffDate}`,{revision,media:media.length});return {ok:true,releaseId:summary.id,revision}});
exports.adminManageRufeMedia=onCall(async req=>{const actor=await requireRole(req,['super_admin']),eventId=clean(req.data?.eventId,120),mediaId=clean(req.data?.mediaId,180),action=clean(req.data?.action,30);const ref=db.doc(`rufeEvents/${eventId}/media/${mediaId}`),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Archivo no encontrado.');if(action==='publication'){await ref.update({includeInPublication:req.data?.includeInPublication===true,updatedAt:FieldValue.serverTimestamp(),updatedBy:actor.uid});await audit(actor,'media.publication',eventId,mediaId,{include:req.data?.includeInPublication===true});return {ok:true}}if(action==='delete'){const m=snap.data();if(m.path)await bucket.file(m.path).delete({ignoreNotFound:true});await ref.delete();await audit(actor,'media.delete',eventId,mediaId);return {ok:true}}throw new HttpsError('invalid-argument','Acción no soportada.');});
