const cfg=window.RUFE_FIREBASE_CONFIG||{};
const EVENT_ID=window.RUFE_EVENT_ID||'san-pedro-sismo-2026';
const configured=Boolean(cfg.apiKey&&cfg.projectId&&cfg.authDomain);
const roleAliases={editor:'editor',validator:'validator',validador:'validator',admin:'admin',administrador:'admin',super_admin:'super_admin','super-admin':'super_admin','super admin':'super_admin',superadmin:'super_admin','super administrador':'super_admin','administrador principal':'super_admin'};
const normalizeRole=r=>roleAliases[String(r||'').trim().toLowerCase()]||String(r||'guest').trim().toLowerCase();
const permitted=['editor','validator','admin','super_admin'];
const slug=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const emit=(name,detail)=>window.dispatchEvent(new CustomEvent(name,{detail}));
let app,auth,db,storage,functions,user=null,profile=null,SDK=null,ready=false,initError=null;
let unsubPublic=null,unsubDraft=null,unsubTerritories=null,unsubWorkflow=null,pendingPublic=null;

function fallbackReport(){
  const D=structuredClone(window.REPORT_DATA||{}),geo=window.TERRITORY_MAP_DATA||[];
  D.territories=(D.territories||[]).map(t=>({...t,...(geo.find(g=>g.sector===t.sector)||{})}));
  D.releases=[{id:'3-0-2026-08-18',version:'3.0',cutoffDate:'2026-08-18',publishedAt:'2026-08-18',changeNote:'Consolidado técnico inicial del portal.',kpis:structuredClone(D.kpis),housing:structuredClone(D.housing)}];
  D.updates=[{id:'3-0-2026-08-18',date:'2026-08-18',version:'3.0',title:'Consolidado técnico v3.0',note:'Corte de información del 18 de agosto de 2026.',status:'published'}];
  D.media=[];D.publication={status:'published',version:'3.0',cutoffDate:'2026-08-18',publishedAt:'2026-08-18'};return D;
}
function assertReady(){if(!ready||!db)throw new Error(initError?'Firebase no pudo conectarse. Revisa la red e intenta nuevamente.':'Firebase todavía se está conectando. Intenta en unos segundos.');}
function hasRole(...roles){return profile?.active===true&&roles.includes(normalizeRole(profile?.role))}
function requireRole(...roles){if(!user)throw new Error('Debes iniciar sesión.');if(!hasRole(...roles))throw new Error('No tienes permisos para esta operación.');}

async function loadSdk(){
  const V='12.16.0',base=`https://www.gstatic.com/firebasejs/${V}/`;
  const [appM,authM,fsM,storageM,functionsM]=await Promise.all([
    import(base+'firebase-app.js'),import(base+'firebase-auth.js'),import(base+'firebase-firestore.js'),import(base+'firebase-storage.js'),import(base+'firebase-functions.js')
  ]);return {...appM,...authM,...fsM,...storageM,...functionsM};
}
async function getProfile(u){if(!u||!db)return null;const a=await SDK.getDoc(SDK.doc(db,'users',u.uid));if(a.exists())return {uid:u.uid,...a.data(),role:normalizeRole(a.data().role)};if(u.email){const b=await SDK.getDoc(SDK.doc(db,'users',u.email));if(b.exists())return {uid:u.uid,legacyId:u.email,...b.data(),role:normalizeRole(b.data().role)}}return {uid:u.uid,email:u.email||'',displayName:u.displayName||'',role:'guest',active:true}}

async function init(){
  if(!configured){initError='missing-config';emit('rufe:status',{ready:false,configured:false});return false}
  try{
    SDK=await loadSdk();app=SDK.initializeApp(cfg);auth=SDK.getAuth(app);db=SDK.getFirestore(app);storage=SDK.getStorage(app);functions=SDK.getFunctions(app,cfg.functionsRegion||'us-central1');ready=true;
    SDK.onAuthStateChanged(auth,async u=>{user=u||null;profile=u?await getProfile(u):null;emit('rufe:auth',{user,profile})});
    emit('rufe:status',{ready:true,configured:true});if(pendingPublic)attachPublic(pendingPublic);return true;
  }catch(e){initError=e;console.warn('RUFE Firebase no disponible; el portal público continúa con la copia local.',e);emit('rufe:status',{ready:false,configured:true,error:e});return false}
}
async function waitReady(){if(ready)return true;for(let i=0;i<40&&!ready&&!initError;i++)await new Promise(r=>setTimeout(r,100));assertReady();return true}
async function loginGoogle(){await waitReady();return SDK.signInWithPopup(auth,new SDK.GoogleAuthProvider())}
async function loginEmail(email,password){await waitReady();return SDK.signInWithEmailAndPassword(auth,email,password)}
async function resetPassword(email){await waitReady();return SDK.sendPasswordResetEmail(auth,email)}
async function logout(){if(auth)await SDK.signOut(auth)}

function attachPublic(callback){if(!ready||!db)return;unsubPublic?.();unsubPublic=SDK.onSnapshot(SDK.doc(db,'rufePublished',EVENT_ID),s=>{if(s.exists())callback({...fallbackReport(),...s.data()},{source:'firebase'});else callback(fallbackReport(),{source:'fallback'})},()=>callback(fallbackReport(),{source:'fallback'}))}
function listenPublic(callback){pendingPublic=callback;callback(fallbackReport(),{source:'fallback'});if(ready)attachPublic(callback);return ()=>unsubPublic?.()}
async function getPublicRelease(releaseId){await waitReady();const id=String(releaseId||'').trim();if(!id)throw new Error('Corte histórico no especificado.');const snap=await SDK.getDoc(SDK.doc(db,'rufePublished',EVENT_ID,'releases',id));return snap.exists()?{...fallbackReport(),...snap.data()}:null}
function listenDraft(callback){assertReady();requireRole('editor','validator','admin','super_admin');unsubDraft?.();unsubDraft=SDK.onSnapshot(SDK.doc(db,'rufeEvents',EVENT_ID,'drafts','current'),s=>callback(s.exists()?s.data():null));return unsubDraft}
function listenTerritories(callback){assertReady();requireRole('editor','validator','admin','super_admin');unsubTerritories?.();unsubTerritories=SDK.onSnapshot(SDK.collection(db,'rufeEvents',EVENT_ID,'territories'),s=>callback(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.sector).localeCompare(String(b.sector),'es'))));return unsubTerritories}
function listenWorkflow(callback){assertReady();requireRole('editor','validator','admin','super_admin');unsubWorkflow?.();unsubWorkflow=SDK.onSnapshot(SDK.doc(db,'rufeEvents',EVENT_ID,'workflow','state'),s=>callback(s.exists()?s.data():null));return unsubWorkflow}
function stopInternalListeners(){unsubDraft?.();unsubTerritories?.();unsubWorkflow?.();unsubDraft=null;unsubTerritories=null;unsubWorkflow=null}

async function saveTerritory(row){await waitReady();requireRole('editor','admin','super_admin');const sector=String(row.sector||'').trim();if(!sector)throw new Error('El territorio es obligatorio.');const clean={sector};['families','people','noHab','destroyed','noState','empty'].forEach(k=>clean[k]=Math.max(0,Number(row[k])||0));clean.lat=row.lat===''||row.lat==null?null:Number(row.lat);clean.lng=row.lng===''||row.lng==null?null:Number(row.lng);clean.precision=row.precision==='verified'?'verified':'reference';clean.reference=String(row.reference||'').trim();clean.source=String(row.source||'').trim();const batch=SDK.writeBatch(db);batch.set(SDK.doc(db,'rufeEvents',EVENT_ID,'territories',slug(sector)),{...clean,updatedAt:SDK.serverTimestamp(),updatedBy:user.uid},{merge:true});batch.set(SDK.doc(db,'rufeEvents',EVENT_ID,'workflow','state'),{revision:SDK.increment(1),reviewStatus:'changes',approvedRevision:null,updatedAt:SDK.serverTimestamp(),updatedBy:user.uid},{merge:true});batch.set(SDK.doc(SDK.collection(db,'rufeEvents',EVENT_ID,'editorActivity')),{action:'territory.update',sector,uid:user.uid,at:SDK.serverTimestamp()});await batch.commit();return clean}
async function saveTerritoriesBulk(rows){await waitReady();requireRole('editor','admin','super_admin');if(!Array.isArray(rows)||!rows.length)throw new Error('No hay filas para importar.');if(rows.length>100)throw new Error('Máximo 100 territorios por importación.');const batch=SDK.writeBatch(db);let count=0;for(const row of rows){const sector=String(row.sector||'').trim();if(!sector)continue;const clean={sector};['families','people','noHab','destroyed','noState','empty'].forEach(k=>clean[k]=Math.max(0,Number(row[k])||0));clean.lat=row.lat===''||row.lat==null?null:Number(row.lat);clean.lng=row.lng===''||row.lng==null?null:Number(row.lng);clean.precision=row.precision==='verified'?'verified':'reference';clean.reference=String(row.reference||'').trim();clean.source=String(row.source||'').trim();batch.set(SDK.doc(db,'rufeEvents',EVENT_ID,'territories',slug(sector)),{...clean,updatedAt:SDK.serverTimestamp(),updatedBy:user.uid},{merge:true});count++}batch.set(SDK.doc(db,'rufeEvents',EVENT_ID,'workflow','state'),{revision:SDK.increment(1),reviewStatus:'changes',approvedRevision:null,updatedAt:SDK.serverTimestamp(),updatedBy:user.uid},{merge:true});batch.set(SDK.doc(SDK.collection(db,'rufeEvents',EVENT_ID,'editorActivity')),{action:'territory.bulk_import',count,uid:user.uid,at:SDK.serverTimestamp()});await batch.commit();return {count}}
async function saveDraft(patch){await waitReady();requireRole('editor','admin','super_admin');const allowed=['draftVersion','draftCutoff','meta','documentControl','executiveSummary','objective','scope','limitations','eventContext','regulatoryFramework','rufeRud','kpis','completeness','componentStatus','housing','housingInterpretation','priorityHousingNarrative','sexDistribution','lifeCycle','locationDeclared','territorialReading','qualityIssues','qualityAssuranceRules','methodology','appliedRules','priorities','prioritizationMatrix','conclusions','annexIndicators','changeNoteDraft'];const clean={};allowed.forEach(k=>{if(patch[k]!==undefined)clean[k]=patch[k]});const batch=SDK.writeBatch(db);batch.set(SDK.doc(db,'rufeEvents',EVENT_ID,'drafts','current'),{...clean,updatedAt:SDK.serverTimestamp(),updatedBy:user.uid},{merge:true});batch.set(SDK.doc(db,'rufeEvents',EVENT_ID,'workflow','state'),{revision:SDK.increment(1),reviewStatus:'changes',approvedRevision:null,updatedAt:SDK.serverTimestamp(),updatedBy:user.uid},{merge:true});batch.set(SDK.doc(SDK.collection(db,'rufeEvents',EVENT_ID,'editorActivity')),{action:'draft.update',uid:user.uid,at:SDK.serverTimestamp()});await batch.commit()}
function initialDraft(){const D=window.REPORT_DATA;return {meta:D.meta,documentControl:D.documentControl,executiveSummary:D.executiveSummary,objective:D.objective,scope:D.scope,limitations:D.limitations,eventContext:D.eventContext,regulatoryFramework:D.regulatoryFramework,rufeRud:D.rufeRud,kpis:D.kpis,completeness:D.completeness,componentStatus:D.componentStatus,housing:D.housing,housingInterpretation:D.housingInterpretation,priorityHousingNarrative:D.priorityHousingNarrative,sexDistribution:D.sexDistribution,lifeCycle:D.lifeCycle,locationDeclared:D.locationDeclared,territorialReading:D.territorialReading||'',qualityIssues:D.qualityIssues,qualityAssuranceRules:D.qualityAssuranceRules,methodology:D.methodology,appliedRules:D.appliedRules,priorities:D.priorities,prioritizationMatrix:D.prioritizationMatrix,conclusions:D.conclusions,annexIndicators:D.annexIndicators,draftVersion:'3.0',draftCutoff:'2026-08-18'}}
async function seedInitialData(){await waitReady();requireRole('super_admin');const D=window.REPORT_DATA,geo=window.TERRITORY_MAP_DATA||[],batch=SDK.writeBatch(db);batch.set(SDK.doc(db,'rufeEvents',EVENT_ID),{name:'Emergencia sísmica San Pedro 2026',municipality:'San Pedro, Valle del Cauca',eventDate:'2026-08-10',active:true,updatedAt:SDK.serverTimestamp()},{merge:true});batch.set(SDK.doc(db,'rufeEvents',EVENT_ID,'drafts','current'),{...initialDraft(),seededAt:SDK.serverTimestamp(),updatedAt:SDK.serverTimestamp(),updatedBy:user.uid},{merge:true});batch.set(SDK.doc(db,'rufeEvents',EVENT_ID,'workflow','state'),{revision:1,reviewStatus:'draft',approvedRevision:null,updatedAt:SDK.serverTimestamp(),updatedBy:user.uid},{merge:true});(D.territories||[]).forEach(t=>{const g=geo.find(x=>x.sector===t.sector)||{};batch.set(SDK.doc(db,'rufeEvents',EVENT_ID,'territories',slug(t.sector)),{...t,lat:g.lat??null,lng:g.lng??null,precision:g.precision||'reference',reference:g.reference||'',source:g.source||'',updatedAt:SDK.serverTimestamp(),updatedBy:user.uid},{merge:true})});await batch.commit();return true}
async function call(name,payload={}){await waitReady();const fn=SDK.httpsCallable(functions,name);return (await fn({eventId:EVENT_ID,...payload})).data}
const createUser=p=>{requireRole('super_admin');return call('adminCreateRufeUser',p)};const manageUser=p=>{requireRole('super_admin');return call('adminManageRufeUser',p)};const validateDraft=()=>{requireRole('editor','validator','admin','super_admin');return call('validateRufeDraft')};const submitForReview=note=>{requireRole('editor','admin','super_admin');return call('submitRufeForReview',{note})};const reviewDraft=(decision,note)=>{requireRole('validator','admin','super_admin');return call('reviewRufeDraft',{decision,note})};const publish=p=>{requireRole('super_admin');return call('publishRufeSnapshot',p)};const manageMedia=p=>{requireRole('super_admin');return call('adminManageRufeMedia',p)};
async function listUsers(){await waitReady();requireRole('super_admin');const s=await SDK.getDocs(SDK.collection(db,'users')),rows=s.docs.map(d=>({docId:d.id,...d.data(),role:normalizeRole(d.data().role)})),out=new Map();for(const x of rows){const key=x.uid||x.email||x.docId;if(!out.has(key)||x.docId===x.uid)out.set(key,x)}return [...out.values()].filter(x=>x.rufeAccess===true||permitted.includes(x.role)).sort((a,b)=>String(a.displayName||a.email).localeCompare(String(b.displayName||b.email),'es'))}
async function listAudit(){await waitReady();requireRole('super_admin');const s=await SDK.getDocs(SDK.query(SDK.collection(db,'rufeAudit'),SDK.orderBy('createdAt','desc'),SDK.limit(150)));return s.docs.map(d=>({id:d.id,...d.data()}))}
async function listMedia(){await waitReady();requireRole('editor','validator','admin','super_admin');const s=await SDK.getDocs(SDK.query(SDK.collection(db,'rufeEvents',EVENT_ID,'media'),SDK.orderBy('createdAt','desc'),SDK.limit(150)));return s.docs.map(d=>({id:d.id,...d.data()}))}
async function uploadMedia(file,{title,type='annex',includeInPublication=false,onProgress}={}){await waitReady();requireRole('super_admin');if(!file)throw new Error('Selecciona un archivo.');if(file.size>40*1024*1024)throw new Error('El archivo supera 40 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-'),path=`rufe-drafts/${EVENT_ID}/${Date.now()}-${safe}`,task=SDK.uploadBytesResumable(SDK.ref(storage,path),file,{contentType:file.type||'application/octet-stream'});await new Promise((resolve,reject)=>task.on('state_changed',s=>onProgress?.(s.totalBytes?Math.round(s.bytesTransferred/s.totalBytes*100):0),reject,resolve));const url=await SDK.getDownloadURL(task.snapshot.ref),rec={title:title||file.name,type,name:file.name,path,url,size:file.size,contentType:file.type||'',includeInPublication:!!includeInPublication,createdAt:SDK.serverTimestamp(),createdBy:user.uid,status:'draft'},r=await SDK.addDoc(SDK.collection(db,'rufeEvents',EVENT_ID,'media'),rec);return {id:r.id,...rec}}
window.RUFE_FIREBASE={configured,EVENT_ID,init,loginGoogle,loginEmail,resetPassword,logout,listenPublic,getPublicRelease,listenDraft,listenTerritories,listenWorkflow,stopInternalListeners,saveTerritory,saveTerritoriesBulk,saveDraft,seedInitialData,createUser,manageUser,validateDraft,submitForReview,reviewDraft,publish,listUsers,listAudit,listMedia,uploadMedia,manageMedia,fallbackReport,normalizeRole,hasRole,get ready(){return ready},get user(){return user},get profile(){return profile}};
init();
