const $=s=>document.querySelector(s);const fmt=n=>Number(n||0).toLocaleString('es-CO');const pct=n=>`${Number(n||0).toFixed(1).replace('.',',')}%`;const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let DATA=null,SOURCE='fallback';const tones={green:'#2f9f6b',orange:'#f0a11e',red:'#d93c45',darkred:'#9e2632',blue:'#0a5be8',gray:'#91a2b5',magenta:'#c63f92',violet:'#7655d9',teal:'#0c9485'};
function shortDate(v){const d=new Date(v);return Number.isNaN(+d)?String(v||'—'):d.toLocaleDateString('es-CO',{day:'2-digit',month:'short',year:'numeric'}).replace('.','')}
function safe(v){return Array.isArray(v)?v:[]}
function render(){if(!DATA)return;const k=DATA.kpis||{},pub=DATA.publication||{},cut=pub.cutoffDate||DATA.meta?.cutoffDate||'2026-08-18';
  $('#reportSubtitle').textContent=DATA.meta?.subtitle||'Avance del diligenciamiento RUFE y censo de familias afectadas';
  $('#coverMeta').innerHTML=`<div><small>EVENTO</small><b>${esc(DATA.meta?.eventDate||'10 de agosto de 2026')}</b></div><div><small>CORTE</small><b>${esc(shortDate(cut))}</b></div><div><small>VERSIÓN</small><b>${esc(pub.version||DATA.meta?.version||'—')}</b></div><div><small>CARÁCTER</small><b>Preliminar operativo</b></div>`;
  $('#coverKpis').innerHTML=[[k.families,'Familias'],[k.nominalPeople,'Personas'],[k.uniquePeopleEstimated,'Únicas estimadas'],[k.territories,'Territorios']].map(x=>`<article><b>${fmt(x[0])}</b><span>${x[1]}</span></article>`).join('');
  $('#executiveSummary').innerHTML=safe(DATA.executiveSummary).map(x=>`<p>${esc(x)}</p>`).join('');
  $('#completionPrint').innerHTML=safe(DATA.completeness).map(x=>`<div class="metric"><label>${esc(x.label)}</label><i><span style="width:${Math.min(100,Number(x.value)||0)}%"></span></i><b>${pct(x.value)}</b></div>`).join('');
  const h=safe(DATA.housing),priority=(h.find(x=>x.label==='No habitable')?.count||0)+(h.find(x=>x.label==='Destruida')?.count||0),families=k.families||1;
  $('#housingPrint').innerHTML=h.map(x=>`<div class="housing-item"><label>${esc(x.label)}</label><i><span style="width:${Math.min(100,(Number(x.count)||0)/families*100)}%;background:${tones[x.tone]||'#0a5be8'}"></span></i><b>${fmt(x.count)} · ${pct((Number(x.count)||0)/families*100)}</b></div>`).join('');
  $('#housingCallout').innerHTML=`<strong>${fmt(priority)}</strong><h3>casos de verificación prioritaria</h3><p>${esc(DATA.priorityHousingNarrative||'')}</p>`;
  $('#housingInterpretationPrint').innerHTML=safe(DATA.housingInterpretation).map(x=>`<div>${esc(x)}</div>`).join('');
  const pop=[['Mujeres',k.women,'#c63f92'],['Hombres',k.men,'#0a5be8'],['0–17 años',k.minors,'#f0a11e'],['60 años y más',k.age60plus,'#2f9f6b'],['Sin documento válido',k.peopleWithoutValidDocument,'#7655d9'],['Fecha nac. inválida',k.invalidBirthDates,'#d93c45']];
  $('#populationPrint').innerHTML=pop.map(x=>`<article class="pop-card" style="background:${x[2]}"><b>${fmt(x[1])}</b><span>${x[0]}</span></article>`).join('');
  const life=safe(DATA.lifeCycle),max=Math.max(1,...life.map(x=>Number(x.count)||0));$('#lifeCyclePrint').innerHTML=life.map(x=>`<div class="age-col"><b>${fmt(x.count)}</b><i style="height:${Math.max(3,(Number(x.count)||0)/max*210)}px"></i><span>${esc(x.label)}</span></div>`).join('');
  $('#territorialReadingPrint').textContent=DATA.territorialReading||'';$('#territoryPrint').innerHTML=safe(DATA.territories).map(t=>`<tr><td><b>${esc(t.sector)}</b></td><td>${fmt(t.families)}</td><td>${fmt(t.people)}</td><td>${fmt(t.noHab)}</td><td>${fmt(t.destroyed)}</td><td>${fmt(t.noState)}</td><td>${fmt(t.empty)}</td><td><b>${fmt((Number(t.noHab)||0)+(Number(t.destroyed)||0))}</b></td></tr>`).join('');
  $('#qualityPrint').innerHTML=safe(DATA.qualityIssues).map(x=>`<article class="issue"><strong>${fmt(x.count)}</strong><h3>${esc(x.label)}</h3><p><b>Riesgo:</b> ${esc(x.risk)}</p><p><b>Tratamiento:</b> ${esc(x.treatment)}</p></article>`).join('');
  $('#methodologyPrint').innerHTML=safe(DATA.methodology).map((x,i)=>`<article class="flow-step"><span>${i+1}</span><h3>${esc(x.title||x.step)}</h3><p>${esc(x.detail||x.description||'')}</p></article>`).join('');
  const nums=(arr)=>safe(arr).map((x,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><p>${esc(typeof x==='string'?x:JSON.stringify(x))}</p></div>`).join('');$('#limitationsPrint').innerHTML=nums(DATA.limitations);$('#qualityRulesPrint').innerHTML=nums(DATA.qualityAssuranceRules);
  $('#prioritiesPrint').innerHTML=safe(DATA.priorities).map((x,i)=>`<article class="priority"><span>${i+1}</span><p>${esc(x)}</p></article>`).join('');$('#matrixPrint').innerHTML=safe(DATA.prioritizationMatrix).map(x=>`<article class="matrix"><h3>${esc(x.level)}</h3><p>${esc(x.criteria)}</p><b>${esc(x.action)}</b></article>`).join('');
  $('#conclusionsPrint').innerHTML=nums(DATA.conclusions);$('#rufeRudPrint').textContent=DATA.rufeRud||'';const dc=DATA.documentControl||{};$('#signaturesPrint').innerHTML=safe(dc.finalSignatures).map(x=>`<div class="signature"><small>${esc(x.role)}</small><b>${esc(x.name)}</b><span>${esc(x.title)}</span></div>`).join('');
  const live=String(SOURCE).startsWith('firebase'),st=$('#printSourceState');st.classList.toggle('live',live);st.querySelector('b').textContent=live?`${SOURCE==='firebase-history'?'Histórico oficial':'Sincronizado'} · corte ${shortDate(cut)}`:`Copia local verificada · corte ${shortDate(cut)}`;
}
$('#printReport').addEventListener('click',()=>window.print());$('#downloadJson').addEventListener('click',()=>{if(!DATA)return;const blob=new Blob([JSON.stringify(DATA,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rufe-san-pedro-${DATA.publication?.cutoffDate||'corte'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});
const F=window.RUFE_FIREBASE,requestedRelease=new URLSearchParams(location.search).get('release');let historicalLoaded=false;if(F)F.listenPublic(async(data,meta)=>{DATA=data;SOURCE=meta.source;render();if(requestedRelease&&meta.source==='firebase'&&!historicalLoaded){historicalLoaded=true;try{const historic=await F.getPublicRelease(requestedRelease);if(historic){DATA=historic;SOURCE='firebase-history';render()}else{historicalLoaded=false;console.warn('El corte histórico solicitado no existe:',requestedRelease)}}catch(e){historicalLoaded=false;console.warn('No fue posible cargar el corte histórico.',e)}}});else{DATA=window.REPORT_DATA;render()}
